### ISSUE TITLE
The full screen feature is not working

### ISSUE THREAD

**Issue by bytebisha** [Morten010/WireUp#7]
There is no effect when I click on the full screen icon

<img width="1624" alt="Screenshot 2024-02-23 at 8 31 34 PM" src="https://github.com/Morten010/WireUp/assets/128947610/393b8480-8c17-4bdf-8943-4024c9504550">

**Comment by Morten010** [comment]
it is not actually a full screen icon its a center icon so it will go and try and go in the center of the tables.

**Comment by Morten010** [comment]
would you want that? and by full screen do you mean remove the sidebar and top nav and make it bigger or just like watching a movie full screen?

**Comment by bytebisha** [comment]
No it was a misunderstanding on my part, sorry

**Comment by Morten010** [comment]
thats alright, thanks for checking my project out. 
have a good day :)
